spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost/voll_med_beta
    username: root
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true

api:
  security:
    secret: ${JWT_SECRET:123456}
#spring.datasource.url=jdbc:mysql://localhost/vollmed_api
#spring.datasource.username=root
#spring.datasource.password=2812
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#server.error.include-stacktrace=never
#
#api.security.secret=${JWT_SECRET:123456}